import {View,Text} from "react-native";
import { Tabs } from 'react-native-collapsible-tab';
import {Header, MenuBar, renderRow, ReSizeWebView} from "./Component";
import {useSafeAreaInsets} from "react-native-safe-area-context";
import {appSize} from "../../../Components/GStyles";
import {SizedWebView} from "react-native-sized-webview";
import React, {useState} from "react";
import WebView from "react-native-webview";


export default function PlayerScreen() {

    const insets =  useSafeAreaInsets()


    const injectedScript = `
      (function() {
        function sendHeight() {
          const height = document.documentElement.scrollHeight || document.body.scrollHeight;
          window.ReactNativeWebView.postMessage(JSON.stringify({ height: height }));
        }
        // 页面加载完成后发送高度
        window.addEventListener('load', sendHeight);
        // 如果内容在加载后可能变化（如点击展开），可监听窗口大小变化
        window.addEventListener('resize', sendHeight);
      })();
    `;

    const [webViewHeight, setWebViewHeight] = useState(200); // 初始高度

    const onMessage = (event) => {
        try {
            const { height } = JSON.parse(event.nativeEvent.data);
            if (height && height > 0) {
                setWebViewHeight(height);
                console.log(height)
            }
        } catch (error) {
            console.warn('Failed to parse height message:', error);
        }
    };

    return(<View style={{flex:1}}>

        <View style={{height:insets.top,width:'100%',backgroundColor:'#fff'}} />

        <Tabs.Container renderHeader={() => <Header />}  renderTabBar={()=><MenuBar />}>
            <Tabs.Tab name="about" label="About">
                <Tabs.ScrollView>
                    <View style={{}} contentContainerStyle={{ flexGrow: 1 }}>

      {/*                  <WebView*/}
      {/*                      source={{ html: `*/}
      {/*  <html>*/}
      {/*    <body>*/}
      {/*      <h1>Privacy policy</h1>*/}
      {/*      <p>Generated by your CMS and sized automatically ✨</p>*/}
      {/*    </body>*/}
      {/*  </html>*/}
      {/*`, }}*/}
      {/*                      style={{ height: webViewHeight }} // 动态设置高度*/}
      {/*                      injectedJavaScript={injectedScript}*/}
      {/*                      onMessage={onMessage}*/}
      {/*                      scrollEnabled={false} // 禁用 WebView 内部滚动，让父容器滚动[reference:11]*/}
      {/*                  />*/}

                    </View>
                </Tabs.ScrollView>
            </Tabs.Tab>
            <Tabs.Tab name="posts" label="Posts">
                <Tabs.FlatList style={{paddingHorizontal:appSize(16),backgroundColor:'#f7f7f7'}} data={[1,2,3,4,5,6,7,8,8,9,9,9,9,9,99,9,9,9,9,9]} renderItem={renderRow} />
            </Tabs.Tab>
        </Tabs.Container>

    </View>)
}
